### ISSUE TITLE
services.php "requirelogin" flags might be wrong,

### ISSUE THREAD

**Issue by danmarsden** [iplusacademy/moodle-paygw_mtnafrica#6]
in your services.php you define the webservices as requiring login:
https://github.com/iplusacademy/moodle-paygw_mtnafrica/blob/main/db/services.php#L35

but the webservices themselves don't do any capability checks.

Typically we look for validate_context calls in webservice functions, (which is the api that does the login check in a webservice.) but... payment gateway apis do often sometimes need to be triggered without a login check.

probably worth you checking to see if the requirelogin flag is actually correct - and if it is try to get a validate_context or require_capability call in there.. (obviously the validate_context call will fail if you tell it to use a course context where the user hasn't been added yet, so be careful not to break the webservice by using the course context)

More info on this in the webservices docs here:
https://moodledev.io/docs/apis/subsystems/external/writing-a-service#context-and-capability-checks

**Comment by iplusacademy** [comment]
I do not understand: payment gateway apis do often sometimes need to be triggered without a login check.
Can you explain?

**Comment by iplusacademy** [comment]
Thanks for the clarification.

The services are only available to users who are logged in.  This is necessary because the endpoint depends on the country/telephone of the user AND the country of the payment gateway. Yes, mobile money is not that mobile.

But which context can be validated?  Before an enrolment we are not in a course or module context but only an authenticated user in system context.  We did not find capabilities on system level to check (user_can_use_enrol_fee or user_can_pay). The only thing we can think of is a check for guestuser or suspended user, but this is already covered by the require_login. Should this be repeated or are we missing the most obvious?

**Comment by danmarsden** [comment]
because you can't just use require_login() inside an external function, 

probably the simplest option in there is to do something like:
        $usercontext = \context_user::instance($USER->id);
        self::validate_context($usercontext);

which should do it.

**Comment by ewallah** [comment]
Done and tested in different environments.
